[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestParticle = "953b605b-f162-4481-8f7f-a191c2bb40e3"

[sources]
TestParticle = {path = ".."}
