name = "TestParticle"
uuid = "953b605b-f162-4481-8f7f-a191c2bb40e3"
version = "0.17.0"
authors = ["Hongyang Zhou <hyzhou@umich.edu>, Tiancheng Liu <liutc@mail.nankai.edu.cn>, and Zijin Zhang <zijin@ucla.edu>"]

[workspace]
projects = ["test", "docs"]

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
VelocityDistributionFunctions = "63a0b508-f74a-48f7-b6e7-0e65849b0078"

[weakdeps]
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[extensions]
TestParticleRecursiveArrayToolsExt = "RecursiveArrayTools"

[compat]
ChunkSplitters = "3"
Elliptic = "1"
ForwardDiff = "0.10, 1"
Interpolations = "0.14, 0.15, 0.16"
LinearAlgebra = "1.9"
Meshes = "0.51, 0.52, 0.53, 0.54, 0.55, 0.56"
MuladdMacro = "0.2.4"
PrecompileTools = "1"
SciMLBase = "2.24"
SpecialFunctions = "1.5, 2"
StaticArrays = "1.2"
Statistics = "1"
Tensors = "1.16.2"
VelocityDistributionFunctions = "0.2.1"
julia = "1.9"
