name = "TestParticle"
uuid = "953b605b-f162-4481-8f7f-a191c2bb40e3"
authors = ["Hongyang Zhou <hyzhou@umich.edu>, and Tiancheng Liu <liutc@mail.nankai.edu.cn>"]
version = "0.4.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
TestParticleMakie = "Makie"

[compat]
Distributions = "0.25"
Elliptic = "1.0"
Interpolations = "0.14"
Makie = "0.17, 0.18, 0.19, 0.20"
Meshes = "0.30, 0.31, 0.32, 0.33, 0.34, 0.35"
PrecompileTools = "1.0"
SciMLBase = "1, 2"
SpecialFunctions = "1.5, 2.0"
StaticArrays = "1.2"
Statistics = "1"
julia = "1.9"

[extras]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OrdinaryDiffEq", "Random", "GLMakie"]
