[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
FieldTracer = "05065131-34d1-456a-ba22-faf972bb2934"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
PairPlots = "43a3c2be-4208-490b-832a-a21dcd55d7da"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
TestParticle = "953b605b-f162-4481-8f7f-a191c2bb40e3"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
VelocityDistributionFunctions = "63a0b508-f74a-48f7-b6e7-0e65849b0078"

[sources]
TestParticle = {path = ".."}

[compat]
DocumenterVitepress = "0.2"
